# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xlzcGuElpTaYMFzVe1rQ5zAaAEvRaF4W
"""

import pandas as pd

# Step 1: Load the dataset
from google.colab import files
uploaded = files.upload()

# Reading the CSV file into a pandas DataFrame
df = pd.read_csv("sales_data.csv")

# Display first 5 rows of the dataset
print("First 5 rows of the dataset:")
print(df.head())

# Step 2: Basic dataset information
print("\nDataset Information:")
print(df.info())

print("\nShape of dataset (rows, columns):")
print(df.shape)

# Step 3: Check for missing values

print("\nMissing values in each column:")
print(df.isnull().sum())

# Step 4: Handle missing values

# Filling numerical missing values with column mean
df_filled = df.fillna(df.mean(numeric_only=True))
print("\nMissing values after handling:")
print(df_filled.isnull().sum())

# Step 5: Calculate metrics
# -----------------------------
# Selecting only numeric columns
numeric_columns = df_filled.select_dtypes(include="number")

# Average (Mean)
average_values = numeric_columns.mean()

# Maximum values
max_values = numeric_columns.max()

# Minimum values
min_values = numeric_columns.min()

print("\nAverage values:")
print(average_values)

print("\nMaximum values:")
print(max_values)

print("\nMinimum values:")
print(min_values)

# Step 6: Summary

print("\nData analysis completed successfully.")

